### ISSUE TITLE
[FE] nft 멤버십 마켓플레이스 페이지

### ISSUE THREAD

**Issue by Moshed-Potato** [codestates/BEB-05-BeautifulCJGG#15]
## 용도
멤버십 nft를 민팅하고, 다른 소유자로부터 구매할 수 있는 페이지를 구현합니다.

## TODO List
* [x] 와이어프레임을 참고해서 전체 틀 잡기
* [x] 멤버십 카드 컴포넌트 만들기
* [ ] mint 페이지 만들기
* [ ] store 페이지 만들기
